### ISSUE TITLE
《祝福》内容错误

### ISSUE THREAD

**Issue by tanukihee** [Stone-Zeng/zhlipsum#7]
https://github.com/CTeX-org/zhlipsum/blob/1cd182a91334a8932640649fd818bf044955726d/zhlipsum-text.dtx#L310

「一切饭菜，只好自『己』做」

似乎互联网上都是自「已」，我还专门去翻了高中课本……

**Comment by tanukihee** [comment]
https://github.com/CTeX-org/zhlipsum/blob/1cd182a91334a8932640649fd818bf044955726d/zhlipsum-text.dtx#L284

「卫婆『于』」，应是「卫婆『子』」

**Comment by stone-zeng** [comment]
Fixed in 6289d1b8e83319543cd0f8cdc14c55105dab0f59 and 9255499c67a901f9990b67c94a5c162cfb28c5fc.
